# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration

extends: default
rules:
  comments:
    min-spaces-from-content: 1
  document-start: disable
  empty-lines:
    max-end: 1
