# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration

extends: default
ignore: |
  node_modules
rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  document-start: disable
  empty-lines:
    max-end: 1
