= sdavids.de Homepage
Sebastian Davids <sdavids@gmx.de>

// Metadata:
:description: Sebastian Davids' Homepage

// Settings:
:sectnums:
:sectanchors:
:sectlinks:
:toc: macro
:hide-uri-scheme:
:source-highlighter: rouge
:rouge-style: github

// Refs:
:uri-contributor-covenant: https://www.contributor-covenant.org
:uri-apache-license: https://www.apache.org/licenses/LICENSE-2.0
:uri-google-style: https://github.com/google/gts
:docker-install-url: https://docs.docker.com/install/
:nvm-install-url: https://github.com/nvm-sh/nvm#installing-and-updating
:fnm-install-url: https://github.com/Schniz/fnm#installation

ifdef::env-browser[:outfilesuffix: .adoc]

ifdef::env-github[]
:outfilesuffix: .adoc
:badges:
endif::[]

ifdef::badges[]
image:https://img.shields.io/github/license/sdavids/sdavids.de-homepage[Apache License,Version 2.0,link={uri-apache-license}]
image:https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg[Contributor Covenant,Version 2.1,link={uri-contributor-covenant}]
image:https://img.shields.io/badge/code%20style-google-blueviolet.svg[Code Style: Google,link={uri-google-style}]
image:https://img.shields.io/osslifecycle/sdavids/sdavids.de-homepage[OSS Lifecycle]
image:https://img.shields.io/maintenance/yes/2023[Maintenance]
image:https://img.shields.io/github/last-commit/sdavids/sdavids.de-homepage[GitHub last commit]
image:http://isitmaintained.com/badge/resolution/sdavids/sdavids.de-homepage.svg[Resolution Time]
image:http://isitmaintained.com/badge/open/sdavids/sdavids.de-homepage.svg[Open Issues]
endif::[]

toc::[]

== License

Apache License, Version 2.0 (link:LICENSE[] or {uri-apache-license}).

=== Contribution

See link:CONTRIBUTING{outfilesuffix}[].

== Code of Conduct

We abide by the {uri-contributor-covenant}[Contributor Covenant, Version 2.1]
and ask that you do as well.

For more information, please see link:CODE_OF_CONDUCT{outfilesuffix}[].

== Development Environment Setup

=== Docker

Install {docker-install-url}[Docker].

=== Node Version Manager

Install {nvm-install-url}[NVM] or {fnm-install-url}[fnm].

=== husky

This repository uses https://typicode.github.io/husky/[husky] for git hooks.

More information:
https://typicode.github.io/husky/troubleshooting.html#command-not-found[Husky - Command not found]

==== nvm

.~/.huskyrc
[source,shell]
----
export NVM_DIR="${HOME}/.nvm"

if [[ -f "${NVM_DIR}/nvm.sh" ]]; then
  source "${NVM_DIR}/nvm.sh"

  if [[ -f ".nvmrc" ]]; then
    nvm use
  fi
fi
----

==== fnm

.~/.huskyrc
[source,shell]
----
if type fnm &>/dev/null; then
  eval "$(fnm env)"

  if [[ -f .node-version || -f .nvmrc ]]; then
    fnm use --silent-if-unchanged
  fi
fi
----

=== jq

==== Linux

[source,shell]
----
$ sudo apt-get install jq
----

==== Mac

[source,shell]
----
$ brew install jq
----

=== brotli

==== Linux

[source,shell]
----
$ sudo apt-get install brotli
----

==== Mac

[source,shell]
----
$ brew install brotli
----

=== zstd

==== Linux

[source,shell]
----
$ sudosudo apt install zstd
----

==== Mac

[source,shell]
----
$ brew install zstd
----

=== shellcheck

==== Linux

[source,shell]
----
$ sudo apt-get install shellcheck
----

==== Mac

[source,shell]
----
$ brew install shellcheck
----

=== gpg

==== Linux

[source,shell]
----
$ sudo apt-get install gpg
----

==== Mac

Install https://gpgtools.org[GPG Suite].

=== easyrsa

==== Linux

[source,shell]
----
$ sudo apt-get install easy-rsa
----

==== Mac

[source,shell]
----
$ brew install easy-rsa
----

== Local Dev

[source,shell]
----
$ cd hp
$ npm i
----

=== Shell 1

[source,shell]
----
$ npm run dev:css
----

=== Shell 2

[source,shell]
----
$ npm run dev
----

=> http://localhost:3000

== Local Deployment

=== Build And Start Apache HTTPD
[source,shell]
----
$ cd hp
$ npm run docker:http:start:with-build
----

=> http://localhost:8080

=== Start Apache HTTPD Without a Build
[source,shell]
----
$ cd hp
$ npm run docker:http:start
----

=> http://localhost:8080

=== Stop Apache HTTPD
[source,shell]
----
$ cd hp
$ npm run docker:http:stop
----
