// SPDX-FileCopyrightText: © 2022 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= sdavids.de Homepage
Sebastian Davids <sdavids@gmx.de>
// Metadata:
:description: Sebastian Davids' Homepage
// Settings:
:sectnums:
:sectanchors:
:sectlinks:
:toc: macro
:toclevels: 3
:toc-placement!:
:hide-uri-scheme:
:source-highlighter: rouge
:rouge-style: github
// Refs:
:uri-contributor-covenant: https://www.contributor-covenant.org
:uri-apache-license: https://www.apache.org/licenses/LICENSE-2.0
:uri-google-style: https://github.com/google/gts
:docker-install-url: https://docs.docker.com/install/
:nvm-install-url: https://github.com/nvm-sh/nvm#installing-and-updating
:fnm-install-url: https://github.com/Schniz/fnm#installation

ifdef::env-browser[:outfilesuffix: .adoc]

ifdef::env-github[]
:outfilesuffix: .adoc
:note-caption: :information_source:
:badges:
endif::[]

ifdef::badges[]
image:https://img.shields.io/github/license/sdavids/sdavids.de-homepage[Apache License,Version 2.0,link={uri-apache-license}]
image:https://img.shields.io/badge/Contributor%20Covenant-2.1-4baaaa.svg[Contributor Covenant,Version 2.1,link={uri-contributor-covenant}]
image:https://img.shields.io/badge/code%20style-google-blueviolet.svg[Code Style: Google,link={uri-google-style}]
image:https://img.shields.io/osslifecycle/sdavids/sdavids.de-homepage[OSS Lifecycle]
image:https://img.shields.io/maintenance/yes/2024[Maintenance]
image:https://img.shields.io/github/last-commit/sdavids/sdavids.de-homepage[GitHub last commit]
image:http://isitmaintained.com/badge/resolution/sdavids/sdavids.de-homepage.svg[Resolution Time]
image:http://isitmaintained.com/badge/open/sdavids/sdavids.de-homepage.svg[Open Issues]
endif::[]

toc::[]

{description}

== License

Apache License, Version 2.0 (link:LICENSE[] or {uri-apache-license}).

=== Contribution

See link:CONTRIBUTING{outfilesuffix}[].

== Code of Conduct

We abide by the {uri-contributor-covenant}[Contributor Covenant, Version 2.1] and ask that you do as well.

For more information, please see link:CODE_OF_CONDUCT{outfilesuffix}[].

== Development Environment Setup

=== Installation

==== DNS

Add `httpd.internal` to your `/etc/hosts`:

./etc/hosts
[source,shell]
----
127.0.0.1       localhost httpd.internal
::1             localhost httpd.internal
----

[NOTE]
====
If you want to change this entry you need to also change:

.httpd/httpd.conf
[source]
----
include::httpd/httpd.conf[tags=server-name]
----

.httpd/httpd-ssl.conf
[source]
----
include::httpd/httpd-ssl.conf[tags=server-name]
----

.hp/scripts/docker-httpd-start.sh
[source,shell]
----
include::hp/scripts/docker-httpd-start.sh[tags=server-name]
----

.hp/package.json
[source,shell]
----
…
  "scripts": {
…
    "cert:copy": "scripts/copy-ca-based-cert.sh certs httpd.internal",
    "cert:create": "scripts/create-ca-based-cert.sh certs 30 httpd.internal",
    "cert:delete": "scripts/delete-ca-based-cert.sh certs httpd.internal",
    "cert:renew": "scripts/renew-ca-based-cert.sh certs 30 httpd.internal",
…
  },
…
----
====

==== Docker

Install {docker-install-url}[Docker].

==== Node Version Manager

Install {fnm-install-url}[fnm] or {nvm-install-url}[NVM].

[NOTE]
====
This repository uses https://typicode.github.io/husky/[husky] for Git hooks.

More information:
https://typicode.github.io/husky/troubleshooting.html#command-not-found[Husky - Command not found]
====

===== fnm

.~/.zprofile
[source,shell]
----
if command -v fnm >/dev/null 2>&1; then
  eval "$(fnm env --use-on-cd)"
fi
----

.~/.config/husky/init.sh
[source,shell]
----
#!/usr/bin/env sh

# vim:ft=zsh

# shellcheck shell=sh disable=SC1091

set -eu

[ -e /etc/zshenv ] && . /etc/zshenv
[ -e "${ZDOTDIR:=${HOME}}/.zshenv" ] && . "${ZDOTDIR:=${HOME}}/.zshenv"
[ -e /etc/zprofile ] && . /etc/zprofile
[ -e "${ZDOTDIR:=${HOME}}/.zprofile" ] && . "${ZDOTDIR:=${HOME}}/.zprofile"
[ -e /etc/zlogin ] && . /etc/zlogin
[ -e "${ZDOTDIR:=${HOME}}/.zlogin" ] && . "${ZDOTDIR:=${HOME}}/.zlogin"
----

===== nvm

.~/.zshrc
[source,shell]
----
export NVM_DIR="${HOME}/.nvm"

[ -s "${NVM_DIR}/nvm.sh" ] && . "${NVM_DIR}/nvm.sh"
[ -s "${NVM_DIR}/bash_completion" ] && . "${NVM_DIR}/bash_completion"

if command -v nvm >/dev/null 2>&1; then
  autoload -U add-zsh-hook
  load-nvmrc() {
    local nvmrc_path="$(nvm_find_nvmrc)"
    if [ -n "${nvmrc_path}" ]; then
      local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")
      if [ "${nvmrc_node_version}" = "N/A" ]; then
        nvm install
      elif [ "${nvmrc_node_version}" != "$(nvm version)" ]; then
        nvm use
      fi
    elif [ -n "$(PWD=$OLDPWD nvm_find_nvmrc)" ] && [ "$(nvm version)" != "$(nvm version default)" ]; then
      echo "Reverting to nvm default version"
      nvm use default
    fi
  }

  add-zsh-hook chpwd load-nvmrc
  load-nvmrc
fi
----

.~/.config/husky/init.sh
[source,shell]
----
#!/usr/bin/env sh

# vim:ft=zsh

# shellcheck shell=sh disable=SC1091

set -eu

[ -e /etc/zshenv ] && . /etc/zshenv
[ -e "${ZDOTDIR:=${HOME}}/.zshenv" ] && . "${ZDOTDIR:=${HOME}}/.zshenv"
[ -e /etc/zprofile ] && . /etc/zprofile
[ -e "${ZDOTDIR:=${HOME}}/.zprofile" ] && . "${ZDOTDIR:=${HOME}}/.zprofile"
[ -e /etc/zlogin ] && . /etc/zlogin
[ -e "${ZDOTDIR:=${HOME}}/.zlogin" ] && . "${ZDOTDIR:=${HOME}}/.zlogin"

export NVM_DIR="${HOME}/.nvm"

if [ -f "${NVM_DIR}/nvm.sh" ]; then
  . "${NVM_DIR}/nvm.sh"

  if [ -f ".nvmrc" ]; then
    nvm use
  fi
fi
----

==== jq

===== Linux

[source,shell]
----
$ sudo apt-get install jq
----

===== Mac

[source,shell]
----
$ brew install jq
----

==== brotli

===== Linux

[source,shell]
----
$ sudo apt-get install brotli
----

===== Mac

[source,shell]
----
$ brew install brotli
----

==== zstd

===== Linux

[source,shell]
----
$ sudo apt install zstd
----

===== Mac

[source,shell]
----
$ brew install zstd
----

==== shellcheck

===== Linux

[source,shell]
----
$ sudo apt-get install shellcheck
----

===== Mac

[source,shell]
----
$ brew install shellcheck
----

==== yamllint

===== Linux

[source,shell]
----
$ sudo apt-get install yamllint
----

===== Mac

[source,shell]
----
$ brew install yamllint
----

==== hadolint

===== Linux

Install https://github.com/hadolint/hadolint?tab=readme-ov-file#install[hadolint].

===== Mac

[source,shell]
----
$ brew install hadolint
----

==== gpg

===== Linux

[source,shell]
----
$ sudo apt-get install gpg
----

===== Mac

Install https://gpgtools.org[GPG Suite].

==== easyrsa

===== Linux

[source,shell]
----
$ sudo apt-get install easy-rsa
----

===== Mac

[source,shell]
----
$ brew install easy-rsa
----

=== Local Development

[source,shell]
----
$ cd hp
$ npm install --no-ignore-scripts
----

==== Shell 1

[source,shell]
----
$ npm run dev:css
----

==== Shell 2

[source,shell]
----
$ npm run dev
----

=> http://localhost:3000

=== Local Deployment

==== Create CA and Certificate

[source,shell]
----
$ cd hp
$ npm run cert:ca:create
$ npm run cert:create
----

==== Create Base Docker Image

[source,shell]
----
$ cd httpd
$ scripts/docker-build.sh
----

==== Build And Start Apache HTTPD

[source,shell]
----
$ cd hp
$ npm run docker:httpd:start:with-build
----

=> http://localhost:8080

==== Start Apache HTTPD Without a Build

[source,shell]
----
$ cd hp
$ npm run docker:httpd:start
----

=> http://localhost:8080

==== Stop Apache HTTPD

[source,shell]
----
$ cd hp
$ npm run docker:httpd:stop
----
