# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

version = 1

SPDX-PackageName = "sdavids.de-homepage"
SPDX-PackageSupplier = "Sebastian Davids <sdavids@gmx.de>"
SPDX-PackageDownloadLocation = "https://github.com/sdavids/sdavids.de-homepage"

[[annotations]]
path = "**/**.png"
SPDX-FileCopyrightText = "© 2022 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "design/logo.afdesign"
SPDX-FileCopyrightText = "© 2022 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["httpd/httpd.conf", "httpd/httpd-ssl.conf"]
SPDX-FileCopyrightText = "© 2022 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["hp/package.json", "hp/package-lock.json"]
SPDX-FileCopyrightText = "© 2022 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "hp/.nvmrc"
SPDX-FileCopyrightText = "© 2022 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "hp/src/favicon.ico"
SPDX-FileCopyrightText = "© 2022 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "hp/src/icon.svg"
SPDX-FileCopyrightText = "© 2023 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["hp/src/sdavids.age", "hp/src/sdavids.gpg"]
SPDX-FileCopyrightText = "© 2023 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["hp/src/.well-known/traffic-advice", "hp/src/site.webmanifest"]
SPDX-FileCopyrightText = "© 2022 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "hp/src/.well-known/security.txt"
SPDX-FileCopyrightText = "© 2023 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["hp/jsconfig.json", "hp/jsconfig.prod.json"]
SPDX-FileCopyrightText = "© 2025 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [".devcontainer/devcontainer-lock.json"]
SPDX-FileCopyrightText = "© 2025 Sebastian Davids <sdavids@gmx.de>"
SPDX-License-Identifier = "Apache-2.0"
