#!/usr/bin/env sh

# shellcheck shell=sh

#
# Copyright (c) 2022-2023, Sebastian Davids
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# yamllint needs to be in $PATH
# https://yamllint.readthedocs.io/en/stable/
#   Mac:
#     brew install yamllint
#   Linux:
#     sudo apt-get install yamllint

export ESLINT_USE_FLAT_CONFIG=false

. "$(dirname -- "$0")/_/husky.sh"

yamllint --strict -c .github/.yamllint.yaml .github

cd hp || exit 1

npx --no lint-staged >&2
