---
# SPDX-FileCopyrightText: © 2025 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

# https://pnpm.io/pnpm-workspace_yaml

useNodeVersion: 22.19.0
engineStrict: true
savePrefix: ""
ignoreScripts: false
cleanupUnusedCatalogs: true
resolutionMode: highest
minimumReleaseAge: 1440 # 1 day
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - unrs-resolver
