---
# SPDX-FileCopyrightText: © 2025 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

# https://pnpm.io/pnpm-workspace_yaml

useNodeVersion: 24.11.1
engineStrict: true
savePrefix: ""
ignoreScripts: false
cleanupUnusedCatalogs: true
onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver
