---
#
# Copyright (c) 2023-2024, Sebastian Davids
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Setup node and install dependencies
description: Setup node and install dependencies
inputs:
  working-directory:
    description: the working directory
    required: false
    default: .
  node-version-file:
    description: the path to the node version file
    required: false
    default: .nvmrc
  dependencies-lock-file:
    description: the path to the dependencies lock file
    required: false
    default: package-lock.json
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache-dependency-path: ${{ inputs.dependencies-lock-file }}
        cache: npm
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci --fund=false --audit=false
